### ISSUE TITLE
Can't Rank Up

### ISSUE THREAD

**Issue by tmoyer** [PrisonTeam/Prison#163]
### Which module are you submitting this issue for?

Ranks

### Describe the issue you are experiencing.
When I run /rankup (Ladder Name) with the required funds, it tells me I cant afford it. I've tried giving myself $10000000+ and I still cannot purchase my $1000 rank. I have tried 3 economy plugins, Craftconomy3, AConomy, and iConomy.

### Describe the steps to reproduce the problem.
Create a rank on a ladder other than default, give yourself the required balance. Then try to rankup to it. For me at least it tells me I cant afford it.

### Anything else we need to know?

I deleted the default ladder, which may be a problem, but I do not know.
When I installed the plugin it didn't come with the modules. I had to manually install the ones on your GitHub pages.

**EDIT:** I moved all my ranks to the default ladder that I found still exists and that didn't fix the problem,

**Comment by GABRYCA** [comment]
Hi,
Just for more info, if you use essentialsX with vault as an economy, this still happen?
Which spigot version are you using?
Have a nice day
GABRYCA

**Comment by tmoyer** [comment]
Im using Spigot 1.12.2, I don't like to use essentials because its hard to control, but ill try it if you think it will help.

**Comment by tmoyer** [comment]
I just found that when I restart the server, Prison throws errors because of luckperms or something like that. Could this be related?
```
29.04 11:52:40 [Server] ERROR Error occurred while enabling Prison v3.2.0 (Is it up to date?)
29.04 11:52:40 [Server] INFO java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
```

**Comment by TheOrangeWhale** [comment]
The version of prison that works with LuckPerms v5.0.x is the pre-release version.  It is named Prison_v3.2.1-alpha.10.jar.  It also works with the older versions of LuckPerms too. Make sure you are usering the latest version of Prison.

**Comment by tmoyer** [comment]
Is that from spigot? I've downloaded the latest version from spigot but it's not named "Prison_v3.2.1-alpha.10". Its just called "Prison". I doubt this is the version you're talking about. If its not the right one can you link the correct one?

**Comment by tmoyer** [comment]
Interesting, so it works with essentials. The original problem is fixed, but I would like to know where I can get the latest build you mentioned.

**Comment by GABRYCA** [comment]
Hi,

It's on the discord server inside the #support-bleeding channel.
We'll release it when everything got fixed and stable.
Click [HERE ](https://discord.gg/396ed5F) to join.

Thank you.
